# Generated by Django 5.1.4 on 2025-01-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('shift', models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Evening')], max_length=1)),
                ('number_phone', models.IntegerField()),
                ('time_log', models.TimeField(help_text='Enter the exact time!')),
            ],
        ),
    ]
